# Generated by Django 2.1.5 on 2019-03-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_city', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_to', models.DateField(verbose_name='To')),
            ],
        ),
    ]
