# Generated by Django 2.1.5 on 2019-03-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190315_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Hotel'),
            preserve_default=False,
        ),
    ]
