# Generated by Django 2.1.5 on 2019-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_suitcase_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='DressCode',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
