# Generated by Django 2.1.5 on 2019-03-21 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20190321_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitcase',
            name='trip',
        ),
        migrations.AddField(
            model_name='suitcase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
