# Generated by Django 2.1.5 on 2019-03-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190315_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='base_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Airport'),
        ),
    ]
