# Generated by Django 2.1.5 on 2019-03-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190315_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_airport',
        ),
    ]
