# Generated by Django 2.1.5 on 2019-03-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_destination_destination_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='base_city',
        ),
    ]
