# Generated by Django 2.1.5 on 2019-03-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_trip_base_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
