# Generated by Django 2.1.5 on 2019-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='base_city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='budget_currency',
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.IntegerField(),
        ),
    ]
