# Generated by Django 2.1.5 on 2019-03-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190315_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='trip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip'),
            preserve_default=False,
        ),
    ]
