# Generated by Django 2.1.5 on 2019-03-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190315_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='trip',
        ),
    ]
