# Generated by Django 2.1.5 on 2019-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190315_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='LAX', max_length=3),
        ),
    ]
