# Generated by Django 2.1.5 on 2019-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_trip_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='My Trip', max_length=250),
        ),
    ]
