# Generated by Django 2.1.5 on 2019-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20190318_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='LAX', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(default='LAX', max_length=3),
        ),
    ]
