# Generated by Django 2.1.5 on 2019-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190318_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out',
            field=models.CharField(max_length=100),
        ),
    ]
