# Generated by Django 2.1.5 on 2019-03-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190318_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='return_date',
        ),
    ]
