# Generated by Django 2.1.5 on 2019-03-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20190319_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='trip',
        ),
    ]
