# Generated by Django 2.1.5 on 2019-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_hotel_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='LAX', max_length=3),
        ),
    ]
