# Generated by Django 2.1.5 on 2019-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_trip_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default='2019-03-19'),
        ),
    ]
