# Generated by Django 2.1.5 on 2019-03-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_trip_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='departure_date',
        ),
    ]
